# Generated by Django 4.0.6 on 2022-07-23 17:25

from django.db import migrations, models
import django.utils.timezone
import pathlib


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIVariable',
            fields=[
                ('key', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=1024)),
                ('tooltip', models.CharField(blank=True, max_length=1024)),
            ],
            options={
                'verbose_name_plural': 'API config',
            },
        ),
        migrations.CreateModel(
            name='GameTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_code', models.CharField(help_text='8-character long tier id sent to the game', max_length=8, unique=True)),
                ('tier_label', models.CharField(help_text='Label for the game tier', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='GameVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=256, unique=True)),
                ('authority_file', models.FileField(blank=True, help_text='The authority .pem key file for the version', null=True, upload_to=pathlib.PurePosixPath('authority'))),
                ('version_hash', models.CharField(db_index=True, max_length=40, unique=True)),
                ('note', models.TextField(blank=True, default='')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='ServerVariable',
            fields=[
                ('key', models.CharField(max_length=1024, primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=1024)),
                ('tooltip', models.CharField(blank=True, max_length=1024)),
            ],
            options={
                'verbose_name_plural': 'Server config',
            },
        ),
    ]
