version: '2'
services:
  server:
    build: .
    ports:
      - "${HOST_API_PORT}:8000"
    environment:
      DJANGO_SUPERUSER_USERNAME: "${DJANGO_SUPERUSER_USERNAME}"
      DJANGO_SUPERUSER_EMAIL: "${DJANGO_SUPERUSER_EMAIL}"
      DJANGO_SUPERUSER_PASSWORD: "${DJANGO_SUPERUSER_PASSWORD}"
      DJANGO_DEBUG: "${DJANGO_DEBUG}"
      DJANGO_SECRET_KEY: "${DJANGO_SECRET_KEY}"
      ALLOWED_HOSTS: "${ALLOWED_HOSTS}"
      CSRF_TRUSTED_ORIGINS: "${CSRF_TRUSTED_ORIGINS}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      BACKER_PLATFORMS: "${BACKER_PLATFORMS}"
    volumes:
      - ./api_server:/app/api_server
      - ./files:/app/files
    links:
      - db
    depends_on:
      - db
    command:
      ["wait-for-it", "db:5432", "--", "./spin-up.sh"]

  db:
    image: "postgres:latest"
    environment:
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - "${HOST_DB_PORT}:5432"
