# Generated by Django 4.0.6 on 2022-07-21 15:20

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Licensee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL of the person associated with this code (Patreon.com personal page)', unique=True)),
                ('email', models.EmailField(blank=True, help_text='Email of the person associated with this code', max_length=254)),
                ('display_name', models.CharField(help_text='Licensee name displayed in the simulator UI', max_length=100)),
                ('note', models.TextField(blank=True, default='')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, help_text='Created timestamp')),
                ('tier', models.ForeignKey(blank=True, help_text='Game benefits tier (derived from Patreon.com tiers)', null=True, on_delete=django.db.models.deletion.RESTRICT, to='config.gametier')),
            ],
        ),
        migrations.CreateModel(
            name='GameCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(help_text='Login ID provided by Unreal Engine', max_length=32)),
                ('note', models.TextField(blank=True, default='', help_text='NOTE: If Instance ID is blank, code request string can be pasted in here to          automatically fill in the data.')),
                ('auth_signature', models.TextField(help_text='Signature for validating the code data')),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now, help_text='Created timestamp')),
                ('code_tier', models.ForeignKey(blank=True, help_text='Game benefits tier stored on code creation', null=True, on_delete=django.db.models.deletion.RESTRICT, to='config.gametier')),
                ('licensee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.licensee')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='config.gameversion')),
            ],
        ),
        migrations.CreateModel(
            name='ArchivedCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(help_text='LoginID provided by Unreal Engine', max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('auth_signature', models.TextField(help_text='Signature for validating the code data')),
                ('code_datetime', models.DateTimeField(help_text='Code creation timestamp')),
                ('archived_datetime', models.DateTimeField(default=django.utils.timezone.now, help_text='Archived timestamp')),
                ('code_tier', models.ForeignKey(blank=True, help_text='Game benefits tier stored on code creation', null=True, on_delete=django.db.models.deletion.RESTRICT, to='config.gametier')),
                ('licensee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='game.licensee')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='config.gameversion')),
            ],
        ),
    ]
